Job:
    run_mode: "Hyperparameter"  
    output_directory: "CALCS/SchNet_tune_gap/"
    load_model: "False"
    hyper_trials: 10
    hyper_resume: "True"   #resume a previous hyperparameter optimization run
    target_index: 4      # HOMO-LUMO gap (target index 4) or Dipole moment (target index 0)
    verbosity: 5
    clear_dir: 1
    
Model:
    model: "SchNet"
    dim1: 100
    dim2: 100
    dim3: [50, 100, 200]
    cutoff: [8, 10]
    pre_fc_count: 1
    gc_count: [1, 2]
    post_fc_count: [1, 2]
    pool: "global_mean_pool"
    dropout_rate: 0.0
    num_epochs: 1000
    lr: [0.00005, 0.0005, 0.005]
    batch_size: [5000, 10000]     # for NVIDIA A100's
    optimizer: "AdamW"
    optimizer_args: {}
    scheduler: "ReduceLROnPlateau"
    scheduler_args: {"mode":"min", "factor":0.9, "patience":10, "min_lr":0.00001, "threshold":0.0002}
    early_stopping_patience: 50
