Job:
    run_mode: "Training"  
    output_directory: "CALCS/MEGNet_train_gap/"
    load_model: "False"
    target_index: 4      # HOMO-LUMO gap (target index 4) or Dipole moment (target index 0)
    verbosity: 5
    clear_dir: 1
    
Model:
    model: "MEGNet"
    dim1: 100
    dim2: 100
    dim3: 150
    pre_fc_count: 1
    gc_count: 4
    gc_fc_count: 1
    post_fc_count: 3
    pool: "global_mean_pool"
    dropout_rate: 0.0
    num_epochs: 1000
    lr: 0.0005
    batch_size: 4096     # for NVIDIA A100's
    optimizer: "AdamW"
    optimizer_args: {}
    scheduler: "ReduceLROnPlateau"
    scheduler_args: {"mode":"min", "factor":0.9, "patience":10, "min_lr":0.00001, "threshold":0.0002}
    early_stopping_patience: 50